create table public.fines (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric(10, 2) not null check (amount > 0),
  created_at timestamptz not null default now()
);