-- Replace __ADMIN_EMAIL__ with the same email used for ADMIN_EMAIL in Vercel
-- before running this file in a new Supabase project.

begin;

create table public.fines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  description text not null,
  amount numeric(10, 2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

alter table public.fines enable row level security;

-- Visitors and signed-in users can read only the public columns.
revoke all privileges on table public.fines from anon, authenticated;
grant select (id, description, amount, created_at)
on public.fines to anon, authenticated;

-- Signed-in users receive write privileges, while RLS restricts their use to
-- the configured administrator account.
grant insert (user_id, description, amount)
on public.fines to authenticated;
grant update (description, amount)
on public.fines to authenticated;
grant delete on public.fines to authenticated;

create policy "Anyone can read fines"
on public.fines for select to anon, authenticated
using (true);

create policy "Admin can add fines"
on public.fines for insert to authenticated
with check (
  lower(coalesce(auth.jwt() ->> 'email', '')) = lower('__ADMIN_EMAIL__')
  and user_id = auth.uid()
);

create policy "Admin can update fines"
on public.fines for update to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = lower('__ADMIN_EMAIL__'))
with check (
  lower(coalesce(auth.jwt() ->> 'email', '')) = lower('__ADMIN_EMAIL__')
  and user_id = auth.uid()
);

create policy "Admin can delete fines"
on public.fines for delete to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = lower('__ADMIN_EMAIL__'));

commit;
