create table public.fines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  description text not null,
  amount numeric(10, 2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

alter table public.fines enable row level security;

create policy "Users can read their own fines"
on public.fines for select to authenticated
using (user_id = auth.uid());

create policy "Users can add their own fines"
on public.fines for insert to authenticated
with check (user_id = auth.uid());