-- Adds the statistics-ready core data model to an existing MVP database.
-- Existing public.fines rows are preserved and extended in place.
--
-- IMPORTANT: replace __ADMIN_EMAIL__ with the same email used for ADMIN_EMAIL
-- in Vercel before running this file in Supabase SQL Editor.

begin;

create or replace function public.is_app_admin()
returns boolean
language sql
stable
set search_path = ''
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = lower('__ADMIN_EMAIL__');
$$;

revoke all on function public.is_app_admin() from public;
grant execute on function public.is_app_admin() to authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null check (length(btrim(name)) > 0),
  jersey_number smallint check (jersey_number between 0 and 99),
  active boolean not null default true,
  joined_on date,
  left_on date,
  photo_url text,
  notes text,
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  constraint players_membership_dates_check
    check (left_on is null or joined_on is null or left_on >= joined_on)
);

create unique index if not exists players_name_unique_ci
on public.players (lower(btrim(name)));

create index if not exists players_active_name_idx
on public.players (active, name);

drop trigger if exists players_set_updated_at on public.players;
create trigger players_set_updated_at
before update on public.players
for each row execute function public.set_updated_at();

create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) > 0),
  start_date date not null,
  end_date date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint seasons_dates_check
    check (end_date is null or end_date >= start_date)
);

drop trigger if exists seasons_set_updated_at on public.seasons;
create trigger seasons_set_updated_at
before update on public.seasons
for each row execute function public.set_updated_at();

create table if not exists public.monthly_periods (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete restrict,
  period_month date not null,
  club_payment_date date,
  payment_deadline date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint monthly_periods_first_day_check
    check (period_month = date_trunc('month', period_month)::date),
  constraint monthly_periods_deadline_check
    check (
      payment_deadline is null
      or club_payment_date is null
      or payment_deadline >= club_payment_date
    ),
  unique (season_id, period_month)
);

drop trigger if exists monthly_periods_set_updated_at on public.monthly_periods;
create trigger monthly_periods_set_updated_at
before update on public.monthly_periods
for each row execute function public.set_updated_at();

create table if not exists public.fine_types (
  id bigint generated by default as identity primary key,
  code text not null unique
    check (code ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text not null default '',
  default_amount numeric(10, 2) not null check (default_amount > 0),
  category text not null check (length(btrim(category)) > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null
);

create index if not exists fine_types_active_category_idx
on public.fine_types (active, category, name);

drop trigger if exists fine_types_set_updated_at on public.fine_types;
create trigger fine_types_set_updated_at
before update on public.fine_types
for each row execute function public.set_updated_at();

-- Create the complete table on a fresh database. On the current MVP database,
-- the following ALTER statements add only the missing columns.
create table if not exists public.fines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  player_id bigint references public.players(id) on delete restrict,
  season_id bigint references public.seasons(id) on delete restrict,
  monthly_period_id bigint references public.monthly_periods(id) on delete restrict,
  fine_type_id bigint references public.fine_types(id) on delete restrict,
  name text not null,
  description text not null default '',
  amount numeric(10, 2) not null check (amount > 0),
  currency text not null default 'EUR',
  default_amount_snapshot numeric(10, 2),
  category_snapshot text,
  note text,
  occurred_at timestamptz not null default now(),
  type text not null default 'normal',
  source text not null default 'manual',
  idempotency_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  voided_at timestamptz,
  voided_by uuid references auth.users(id) on delete set null,
  void_reason text
);

alter table public.fines
  add column if not exists player_id bigint references public.players(id) on delete restrict,
  add column if not exists season_id bigint references public.seasons(id) on delete restrict,
  add column if not exists monthly_period_id bigint references public.monthly_periods(id) on delete restrict,
  add column if not exists fine_type_id bigint references public.fine_types(id) on delete restrict,
  add column if not exists name text,
  add column if not exists currency text not null default 'EUR',
  add column if not exists default_amount_snapshot numeric(10, 2),
  add column if not exists category_snapshot text,
  add column if not exists note text,
  add column if not exists occurred_at timestamptz,
  add column if not exists type text not null default 'normal',
  add column if not exists source text not null default 'manual',
  add column if not exists idempotency_key text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists updated_by uuid references auth.users(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists voided_by uuid references auth.users(id) on delete set null,
  add column if not exists void_reason text;

-- Preserve the meaning and date of existing MVP rows.
update public.fines
set name = description
where name is null;

update public.fines
set occurred_at = created_at
where occurred_at is null;

alter table public.fines alter column name set not null;
alter table public.fines alter column occurred_at set default now();
alter table public.fines alter column occurred_at set not null;

-- Snapshot catalogue text/defaults into each event. This keeps historical
-- records understandable even when a fine type is renamed or its default
-- amount changes later. It also keeps the current MVP API working by using its
-- description as the event name until the player/fine-type UI is added.
create or replace function public.prepare_fine_event()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  catalogue_name text;
  catalogue_description text;
  catalogue_default_amount numeric(10, 2);
  catalogue_category text;
begin
  if new.fine_type_id is not null then
    select name, description, default_amount, category
    into catalogue_name, catalogue_description, catalogue_default_amount, catalogue_category
    from public.fine_types
    where id = new.fine_type_id;
  end if;

  new.name = coalesce(
    nullif(btrim(new.name), ''),
    catalogue_name,
    nullif(btrim(new.description), '')
  );
  new.description = coalesce(
    nullif(btrim(new.description), ''),
    catalogue_description,
    ''
  );
  new.default_amount_snapshot = coalesce(
    new.default_amount_snapshot,
    catalogue_default_amount
  );
  new.category_snapshot = coalesce(
    nullif(btrim(new.category_snapshot), ''),
    catalogue_category
  );

  if new.name is null then
    raise exception 'A fine must have a name or description.';
  end if;

  return new;
end;
$$;

drop trigger if exists fines_prepare_event on public.fines;
create trigger fines_prepare_event
before insert on public.fines
for each row execute function public.prepare_fine_event();

do $migration$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.fines'::regclass
      and conname = 'fines_currency_check'
  ) then
    alter table public.fines add constraint fines_currency_check
      check (currency ~ '^[A-Z]{3}$');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.fines'::regclass
      and conname = 'fines_default_amount_snapshot_check'
  ) then
    alter table public.fines add constraint fines_default_amount_snapshot_check
      check (default_amount_snapshot is null or default_amount_snapshot > 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.fines'::regclass
      and conname = 'fines_type_check'
  ) then
    alter table public.fines add constraint fines_type_check
      check (type in ('normal', 'late_payment'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.fines'::regclass
      and conname = 'fines_source_check'
  ) then
    alter table public.fines add constraint fines_source_check
      check (source in ('manual', 'automatic', 'import'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.fines'::regclass
      and conname = 'fines_metadata_object_check'
  ) then
    alter table public.fines add constraint fines_metadata_object_check
      check (jsonb_typeof(metadata) = 'object');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.fines'::regclass
      and conname = 'fines_void_reason_check'
  ) then
    alter table public.fines add constraint fines_void_reason_check
      check (voided_at is null or length(btrim(void_reason)) > 0);
  end if;
end
$migration$;

create index if not exists fines_player_occurred_at_idx
on public.fines (player_id, occurred_at desc);

create index if not exists fines_season_occurred_at_idx
on public.fines (season_id, occurred_at desc);

create index if not exists fines_monthly_period_player_idx
on public.fines (monthly_period_id, player_id);

create index if not exists fines_type_occurred_at_idx
on public.fines (fine_type_id, occurred_at desc);

create index if not exists fines_kind_occurred_at_idx
on public.fines (type, occurred_at desc);

create unique index if not exists fines_idempotency_key_unique
on public.fines (idempotency_key)
where idempotency_key is not null;

drop trigger if exists fines_set_updated_at on public.fines;
create trigger fines_set_updated_at
before update on public.fines
for each row execute function public.set_updated_at();

-- Seed the names currently stored in seed/players.json. This is repeatable.
insert into public.players (name, active)
values
  ('Martin', true),
  ('Šéfko', true),
  ('Matino', true),
  ('Samo', true),
  ('Lukáš', true),
  ('Leon', true),
  ('Alex', true),
  ('Janči', true),
  ('Rado', true),
  ('Šimon', true),
  ('Roman', true),
  ('Peter', true),
  ('Braňo', true)
on conflict do nothing;

alter table public.players enable row level security;
alter table public.seasons enable row level security;
alter table public.monthly_periods enable row level security;
alter table public.fine_types enable row level security;
alter table public.fines enable row level security;

revoke all privileges on table public.players from anon, authenticated;
revoke all privileges on table public.seasons from anon, authenticated;
revoke all privileges on table public.monthly_periods from anon, authenticated;
revoke all privileges on table public.fine_types from anon, authenticated;
revoke all privileges on table public.fines from anon, authenticated;

grant select (id, name, jersey_number, active, joined_on, left_on, photo_url, created_at, updated_at)
on public.players to anon, authenticated;
grant select on public.seasons to anon, authenticated;
grant select on public.monthly_periods to anon, authenticated;
grant select (id, code, name, description, default_amount, category, active, created_at, updated_at)
on public.fine_types to anon, authenticated;
grant select (
  id, player_id, season_id, monthly_period_id, fine_type_id, name,
  description, amount, currency, default_amount_snapshot, category_snapshot,
  note, occurred_at, type, source, created_at, updated_at
)
on public.fines to anon, authenticated;
grant select (user_id, metadata, voided_at, voided_by, void_reason)
on public.fines to authenticated;

grant insert (name, jersey_number, active, joined_on, left_on, photo_url, notes, metadata, created_by, updated_by)
on public.players to authenticated;
grant update (name, jersey_number, active, joined_on, left_on, photo_url, notes, metadata, updated_by)
on public.players to authenticated;

grant insert on public.seasons to authenticated;
grant update on public.seasons to authenticated;
grant insert on public.monthly_periods to authenticated;
grant update on public.monthly_periods to authenticated;
grant insert on public.fine_types to authenticated;
grant update on public.fine_types to authenticated;

grant insert (
  user_id, player_id, season_id, monthly_period_id, fine_type_id, name,
  description, amount, currency, default_amount_snapshot, category_snapshot,
  note, occurred_at, type, source, idempotency_key, metadata
)
on public.fines to authenticated;
grant update (
  player_id, season_id, monthly_period_id, fine_type_id, name, description,
  amount, currency, default_amount_snapshot, category_snapshot, note,
  occurred_at, type, source, metadata, updated_by, voided_at, voided_by,
  void_reason
)
on public.fines to authenticated;

grant usage, select on sequence
  public.players_id_seq,
  public.seasons_id_seq,
  public.monthly_periods_id_seq,
  public.fine_types_id_seq,
  public.fines_id_seq
to authenticated;

drop policy if exists "Public can read players" on public.players;
drop policy if exists "Admin can add players" on public.players;
drop policy if exists "Admin can update players" on public.players;
create policy "Public can read players"
on public.players for select to anon, authenticated using (true);
create policy "Admin can add players"
on public.players for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update players"
on public.players for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

drop policy if exists "Public can read seasons" on public.seasons;
drop policy if exists "Admin can add seasons" on public.seasons;
drop policy if exists "Admin can update seasons" on public.seasons;
create policy "Public can read seasons"
on public.seasons for select to anon, authenticated using (true);
create policy "Admin can add seasons"
on public.seasons for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update seasons"
on public.seasons for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

drop policy if exists "Public can read monthly periods" on public.monthly_periods;
drop policy if exists "Admin can add monthly periods" on public.monthly_periods;
drop policy if exists "Admin can update monthly periods" on public.monthly_periods;
create policy "Public can read monthly periods"
on public.monthly_periods for select to anon, authenticated using (true);
create policy "Admin can add monthly periods"
on public.monthly_periods for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update monthly periods"
on public.monthly_periods for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

drop policy if exists "Public can read fine types" on public.fine_types;
drop policy if exists "Admin can add fine types" on public.fine_types;
drop policy if exists "Admin can update fine types" on public.fine_types;
create policy "Public can read fine types"
on public.fine_types for select to anon, authenticated using (true);
create policy "Admin can add fine types"
on public.fine_types for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update fine types"
on public.fine_types for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

drop policy if exists "Users can read their own fines" on public.fines;
drop policy if exists "Users can add their own fines" on public.fines;
drop policy if exists "Anyone can read fines" on public.fines;
drop policy if exists "Admin can read all fines" on public.fines;
drop policy if exists "Admin can add fines" on public.fines;
drop policy if exists "Admin can update fines" on public.fines;
drop policy if exists "Admin can delete fines" on public.fines;

create policy "Anyone can read fines"
on public.fines for select to anon, authenticated
using (voided_at is null);

create policy "Admin can read all fines"
on public.fines for select to authenticated
using (public.is_app_admin());

create policy "Admin can add fines"
on public.fines for insert to authenticated
with check (public.is_app_admin() and user_id = auth.uid());

create policy "Admin can update fines"
on public.fines for update to authenticated
using (public.is_app_admin())
with check (public.is_app_admin());

commit;
