-- Adds the team calendar, item obligations, exceptions, objections and credits.
-- Run after database/003-fine-calculation-rules.sql.

begin;

alter table public.players
  add column if not exists birth_month smallint,
  add column if not exists birth_day smallint;

do $migration$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.players'::regclass
      and conname = 'players_birthday_check'
  ) then
    alter table public.players add constraint players_birthday_check
      check (
        (birth_month is null and birth_day is null)
        or
        (
          birth_month is not null
          and birth_day is not null
          and
          birth_month between 1 and 12
          and birth_day between 1 and 31
          and extract(month from make_date(2000, birth_month, birth_day)) = birth_month
          and extract(day from make_date(2000, birth_month, birth_day)) = birth_day
        )
      );
  end if;
end
$migration$;

create table if not exists public.team_events (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete restrict,
  code text not null unique check (code ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  event_type text not null check (event_type in ('training', 'match', 'other')),
  starts_at timestamptz not null,
  ends_at timestamptz,
  attendance_scope text not null
    check (attendance_scope in ('full_team', 'partial_team')),
  status text not null default 'scheduled'
    check (status in ('scheduled', 'cancelled', 'completed')),
  location text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  constraint team_events_times_check
    check (ends_at is null or ends_at > starts_at)
);

create index if not exists team_events_season_date_idx
on public.team_events (season_id, starts_at);

drop trigger if exists team_events_set_updated_at on public.team_events;
create trigger team_events_set_updated_at
before update on public.team_events
for each row execute function public.set_updated_at();

create table if not exists public.team_event_players (
  event_id bigint not null references public.team_events(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (event_id, player_id)
);

create table if not exists public.obligation_types (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text not null default '',
  item_name text not null check (length(btrim(item_name)) > 0),
  recurrence text not null check (recurrence in ('once', 'annual')),
  daily_penalty_amount numeric(10, 2) not null default 0
    check (daily_penalty_amount >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists obligation_types_set_updated_at on public.obligation_types;
create trigger obligation_types_set_updated_at
before update on public.obligation_types
for each row execute function public.set_updated_at();

insert into public.obligation_types (
  code, name, description, item_name, recurrence, daily_penalty_amount, active
)
values
  (
    'new-arrival-beer', 'Prískočné',
    'Nový hráč prinesie fľašu alkoholického alebo nealkoholického piva.',
    'bottle of beer', 'once', 0, true
  ),
  (
    'birthday-snack', 'Narodeninové občerstvenie',
    'Hráč prinesie občerstvenie na pridelený celotímový tréning alebo zápas.',
    'snack', 'annual', 1, true
  )
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  item_name = excluded.item_name,
  recurrence = excluded.recurrence,
  daily_penalty_amount = excluded.daily_penalty_amount,
  active = excluded.active,
  updated_at = now();

create table if not exists public.player_obligations (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete restrict,
  season_id bigint not null references public.seasons(id) on delete restrict,
  obligation_type_id bigint not null references public.obligation_types(id) on delete restrict,
  trigger_date date,
  scheduled_event_id bigint references public.team_events(id) on delete set null,
  due_at timestamptz,
  status text not null default 'planned'
    check (status in ('planned', 'due', 'fulfilled', 'cancelled', 'waived')),
  schedule_mode text not null default 'automatic'
    check (schedule_mode in ('automatic', 'manual')),
  scheduling_note text,
  fulfilled_at timestamptz,
  fulfilled_note text,
  cancelled_at timestamptz,
  cancelled_by uuid references auth.users(id) on delete set null,
  cancellation_reason text,
  waived_at timestamptz,
  waived_by uuid references auth.users(id) on delete set null,
  waiver_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null references auth.users(id) on delete restrict,
  updated_by uuid references auth.users(id) on delete set null,
  unique (player_id, season_id, obligation_type_id, trigger_date)
);

create index if not exists player_obligations_due_idx
on public.player_obligations (status, due_at);

create index if not exists player_obligations_event_idx
on public.player_obligations (scheduled_event_id);

create or replace function public.validate_obligation_event()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  assigned_event public.team_events%rowtype;
begin
  if new.scheduled_event_id is null then
    return new;
  end if;

  select * into assigned_event
  from public.team_events
  where id = new.scheduled_event_id;
  if not found
    or assigned_event.status <> 'scheduled'
    or assigned_event.attendance_scope <> 'full_team' then
    raise exception 'Obligations can only use a scheduled full-team event.';
  end if;
  if new.season_id <> assigned_event.season_id then
    raise exception 'The obligation and assigned event must use the same season.';
  end if;
  new.due_at = assigned_event.starts_at;
  return new;
end;
$$;

drop trigger if exists player_obligations_validate_event on public.player_obligations;
create trigger player_obligations_validate_event
before insert or update of scheduled_event_id, season_id, due_at
on public.player_obligations
for each row execute function public.validate_obligation_event();

drop trigger if exists player_obligations_set_updated_at on public.player_obligations;
create trigger player_obligations_set_updated_at
before update on public.player_obligations
for each row execute function public.set_updated_at();

create table if not exists public.obligation_exceptions (
  id bigint generated by default as identity primary key,
  obligation_id bigint not null references public.player_obligations(id) on delete restrict,
  custom_due_at timestamptz,
  penalties_paused_until date,
  penalties_waived boolean not null default false,
  reason text not null check (length(btrim(reason)) > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users(id) on delete restrict
);

create index if not exists obligation_exceptions_active_idx
on public.obligation_exceptions (obligation_id, active);

create table if not exists public.obligation_events (
  id bigint generated by default as identity primary key,
  obligation_id bigint not null references public.player_obligations(id) on delete restrict,
  event_type text not null
    check (event_type in ('created', 'rescheduled', 'fulfilled', 'cancelled', 'waived', 'reopened')),
  from_event_id bigint references public.team_events(id) on delete set null,
  to_event_id bigint references public.team_events(id) on delete set null,
  old_due_at timestamptz,
  new_due_at timestamptz,
  note text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.objections (
  id bigint generated by default as identity primary key,
  fine_id bigint not null unique references public.fines(id) on delete restrict,
  player_id bigint not null references public.players(id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'cancelled')),
  reason text not null check (length(btrim(reason)) > 0),
  filing_fee_amount numeric(10, 2) not null default 1
    check (filing_fee_amount > 0),
  accepted_credit_amount numeric(10, 2) not null default 2
    check (accepted_credit_amount > 0),
  fee_fine_id bigint references public.fines(id) on delete restrict,
  resolution_note text,
  submitted_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_by uuid not null references auth.users(id) on delete restrict,
  resolved_by uuid references auth.users(id) on delete set null
);

create index if not exists objections_status_idx
on public.objections (status, submitted_at desc);

create table if not exists public.financial_adjustments (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete restrict,
  season_id bigint references public.seasons(id) on delete restrict,
  monthly_period_id bigint references public.monthly_periods(id) on delete restrict,
  objection_id bigint references public.objections(id) on delete restrict,
  kind text not null
    check (kind in ('objection_credit', 'manual_credit', 'manual_charge')),
  amount numeric(10, 2) not null check (amount <> 0),
  description text not null check (length(btrim(description)) > 0),
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users(id) on delete restrict,
  unique (objection_id, kind)
);

-- Negative adjustments reduce what a player owes. An accepted objection uses
-- -2 EUR, while its 1 EUR filing-fee fine remains, producing a net 1 EUR credit.

alter table public.fine_types
  add column if not exists system_managed boolean not null default false;

insert into public.fine_types (
  code, name, description, calculation_mode, default_amount, unit_name,
  match_day_only, double_on_match_day, match_day_multiplier, category,
  active, system_managed
)
values
  (
    'objection-filing-fee', 'Poplatok za námietku',
    'Poplatok za podanie námietky voči pokute.',
    'fixed', 1, null, false, false, 2, 'Administration', true, true
  ),
  (
    'birthday-obligation-late', 'Neprinesené narodeninové občerstvenie',
    'Automatická denná pokuta, kým hráč nesplní narodeninovú povinnosť.',
    'fixed', 1, null, false, false, 2, 'Obligation', true, true
  )
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  calculation_mode = excluded.calculation_mode,
  default_amount = excluded.default_amount,
  unit_name = excluded.unit_name,
  match_day_only = excluded.match_day_only,
  double_on_match_day = excluded.double_on_match_day,
  match_day_multiplier = excluded.match_day_multiplier,
  category = excluded.category,
  active = excluded.active,
  system_managed = excluded.system_managed,
  updated_at = now();

alter table public.fines
  add column if not exists obligation_id bigint
    references public.player_obligations(id) on delete restrict,
  add column if not exists objection_id bigint
    references public.objections(id) on delete restrict;

alter table public.fines drop constraint if exists fines_type_check;
alter table public.fines add constraint fines_type_check
  check (type in ('normal', 'late_payment', 'obligation_penalty', 'objection_fee'));

create index if not exists fines_obligation_idx
on public.fines (obligation_id, occurred_at);

create index if not exists fines_objection_idx
on public.fines (objection_id);

create or replace function public.move_obligations_with_event()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  replacement_event_id bigint;
  replacement_starts_at timestamptz;
begin
  if new.status = 'scheduled' and new.attendance_scope = 'full_team' then
    insert into public.obligation_events (
      obligation_id, event_type, from_event_id, to_event_id,
      old_due_at, new_due_at, note
    )
    select
      id, 'rescheduled', old.id, new.id, due_at, new.starts_at,
      'Team event date/time changed.'
    from public.player_obligations
    where scheduled_event_id = new.id
      and status in ('planned', 'due')
      and due_at is distinct from new.starts_at;

    update public.player_obligations
    set due_at = new.starts_at,
        updated_at = now(),
        scheduling_note = 'Moved automatically with team event.'
    where scheduled_event_id = new.id
      and status in ('planned', 'due');
    return new;
  end if;

  select id, starts_at
  into replacement_event_id, replacement_starts_at
  from public.team_events
  where season_id = new.season_id
    and id <> new.id
    and status = 'scheduled'
    and attendance_scope = 'full_team'
    and starts_at >= old.starts_at
  order by starts_at
  limit 1;

  insert into public.obligation_events (
    obligation_id, event_type, from_event_id, to_event_id,
    old_due_at, new_due_at, note
  )
  select
    id, 'rescheduled', new.id, replacement_event_id, due_at,
    replacement_starts_at,
    case
      when replacement_event_id is null
        then 'Original event became ineligible; no replacement was available.'
      else 'Original event became ineligible; moved to the next full-team event.'
    end
  from public.player_obligations
  where scheduled_event_id = new.id
    and status in ('planned', 'due');

  update public.player_obligations
  set scheduled_event_id = replacement_event_id,
      due_at = replacement_starts_at,
      status = 'planned',
      updated_at = now(),
      scheduling_note = case
        when replacement_event_id is null
          then 'Original event became ineligible; administrator must choose a replacement.'
        else 'Moved automatically because the original event became ineligible.'
      end
  where scheduled_event_id = new.id
    and status in ('planned', 'due');

  return new;
end;
$$;

drop trigger if exists team_events_move_obligations on public.team_events;
create trigger team_events_move_obligations
after update of starts_at, status, attendance_scope on public.team_events
for each row
when (
  old.starts_at is distinct from new.starts_at
  or old.status is distinct from new.status
  or old.attendance_scope is distinct from new.attendance_scope
)
execute function public.move_obligations_with_event();

create or replace function public.submit_objection(
  requested_fine_id bigint,
  objection_reason text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  original_fine public.fines%rowtype;
  filing_type public.fine_types%rowtype;
  new_objection_id bigint;
  new_fee_fine_id bigint;
begin
  if not public.is_app_admin() then
    raise exception 'Admin access required.';
  end if;
  if length(btrim(objection_reason)) = 0 then
    raise exception 'An objection reason is required.';
  end if;

  select * into original_fine
  from public.fines
  where id = requested_fine_id and voided_at is null;
  if not found then
    raise exception 'The original fine was not found or is already voided.';
  end if;

  select * into filing_type
  from public.fine_types
  where code = 'objection-filing-fee' and active = true;

  insert into public.objections (
    fine_id, player_id, reason, created_by
  ) values (
    original_fine.id, original_fine.player_id, btrim(objection_reason), auth.uid()
  ) returning id into new_objection_id;

  update public.fines
  set objection_id = new_objection_id,
      updated_by = auth.uid()
  where id = original_fine.id;

  insert into public.fines (
    user_id, player_id, season_id, monthly_period_id, fine_type_id, name,
    description, amount, occurred_at, type, source, objection_id
  ) values (
    auth.uid(), original_fine.player_id, original_fine.season_id,
    original_fine.monthly_period_id, filing_type.id, filing_type.name,
    filing_type.description, 1, now(), 'objection_fee', 'manual',
    new_objection_id
  ) returning id into new_fee_fine_id;

  update public.objections
  set fee_fine_id = new_fee_fine_id
  where id = new_objection_id;

  return new_objection_id;
end;
$$;

create or replace function public.resolve_objection(
  requested_objection_id bigint,
  decision text,
  decision_note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  objection_record public.objections%rowtype;
  original_fine public.fines%rowtype;
begin
  if not public.is_app_admin() then
    raise exception 'Admin access required.';
  end if;
  if decision not in ('accepted', 'rejected') then
    raise exception 'Decision must be accepted or rejected.';
  end if;

  select * into objection_record
  from public.objections
  where id = requested_objection_id
  for update;
  if not found or objection_record.status <> 'pending' then
    raise exception 'The objection was not found or is already resolved.';
  end if;

  select * into original_fine
  from public.fines
  where id = objection_record.fine_id;

  if decision = 'accepted' then
    update public.fines
    set voided_at = now(),
        voided_by = auth.uid(),
        void_reason = 'Accepted objection #' || objection_record.id
    where id = original_fine.id and voided_at is null;

    insert into public.financial_adjustments (
      player_id, season_id, monthly_period_id, objection_id, kind, amount,
      description, created_by
    ) values (
      objection_record.player_id, original_fine.season_id,
      original_fine.monthly_period_id, objection_record.id,
      'objection_credit', -objection_record.accepted_credit_amount,
      'Credit for accepted objection #' || objection_record.id,
      auth.uid()
    );
  end if;

  update public.objections
  set status = decision,
      resolution_note = nullif(btrim(decision_note), ''),
      resolved_at = now(),
      resolved_by = auth.uid()
  where id = objection_record.id;
end;
$$;

revoke all on function public.submit_objection(bigint, text) from public;
revoke all on function public.resolve_objection(bigint, text, text) from public;
grant execute on function public.submit_objection(bigint, text) to authenticated;
grant execute on function public.resolve_objection(bigint, text, text) to authenticated;

alter table public.team_events enable row level security;
alter table public.team_event_players enable row level security;
alter table public.obligation_types enable row level security;
alter table public.player_obligations enable row level security;
alter table public.obligation_exceptions enable row level security;
alter table public.obligation_events enable row level security;
alter table public.objections enable row level security;
alter table public.financial_adjustments enable row level security;

grant select (
  id, season_id, code, name, event_type, starts_at, ends_at,
  attendance_scope, status, location, notes, created_at, updated_at
)
on public.team_events to anon, authenticated;
grant select on public.team_event_players to anon, authenticated;
grant select on public.obligation_types to anon, authenticated;
grant select (
  id, player_id, season_id, obligation_type_id, trigger_date,
  scheduled_event_id, due_at, status, schedule_mode, scheduling_note,
  fulfilled_at, fulfilled_note, created_at, updated_at
)
on public.player_obligations to anon, authenticated;
grant select (id, obligation_id, custom_due_at, penalties_paused_until, penalties_waived, active)
on public.obligation_exceptions to anon, authenticated;
grant select (
  id, obligation_id, event_type, from_event_id, to_event_id,
  old_due_at, new_due_at, note, created_at
)
on public.obligation_events to anon, authenticated;
grant select (
  id, fine_id, player_id, status, reason, filing_fee_amount,
  accepted_credit_amount, fee_fine_id, resolution_note, submitted_at, resolved_at
)
on public.objections to anon, authenticated;
grant select (
  id, player_id, season_id, monthly_period_id, objection_id, kind,
  amount, description, occurred_at, created_at
)
on public.financial_adjustments to anon, authenticated;

grant insert, update on public.team_events to authenticated;
grant insert, update, delete on public.team_event_players to authenticated;
grant insert, update on public.obligation_types to authenticated;
grant insert, update on public.player_obligations to authenticated;
grant insert, update on public.obligation_exceptions to authenticated;
grant insert on public.obligation_events to authenticated;
grant insert, update on public.objections to authenticated;
grant insert on public.financial_adjustments to authenticated;
grant update (birth_month, birth_day) on public.players to authenticated;
grant select (birth_month, birth_day) on public.players to authenticated;
grant select (system_managed) on public.fine_types to anon, authenticated;
grant insert (system_managed), update (system_managed)
on public.fine_types to authenticated;
grant select (obligation_id, objection_id) on public.fines to anon, authenticated;
grant insert, update (obligation_id, objection_id) on public.fines to authenticated;

grant usage, select on sequence
  public.team_events_id_seq,
  public.obligation_types_id_seq,
  public.player_obligations_id_seq,
  public.obligation_exceptions_id_seq,
  public.obligation_events_id_seq,
  public.objections_id_seq,
  public.financial_adjustments_id_seq
to authenticated;

create policy "Public can read team events"
on public.team_events for select to anon, authenticated using (true);
create policy "Admin can add team events"
on public.team_events for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update team events"
on public.team_events for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

create policy "Public can read event players"
on public.team_event_players for select to anon, authenticated using (true);
create policy "Admin can add event players"
on public.team_event_players for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update event players"
on public.team_event_players for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());
create policy "Admin can remove event players"
on public.team_event_players for delete to authenticated using (public.is_app_admin());

create policy "Public can read obligation types"
on public.obligation_types for select to anon, authenticated using (true);
create policy "Admin can add obligation types"
on public.obligation_types for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update obligation types"
on public.obligation_types for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

create policy "Public can read obligations"
on public.player_obligations for select to anon, authenticated using (true);
create policy "Admin can add obligations"
on public.player_obligations for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update obligations"
on public.player_obligations for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

create policy "Public can read obligation exceptions"
on public.obligation_exceptions for select to anon, authenticated using (true);
create policy "Admin can add obligation exceptions"
on public.obligation_exceptions for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update obligation exceptions"
on public.obligation_exceptions for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

create policy "Public can read obligation events"
on public.obligation_events for select to anon, authenticated using (true);
create policy "Admin can add obligation events"
on public.obligation_events for insert to authenticated with check (public.is_app_admin());

create policy "Public can read objections"
on public.objections for select to anon, authenticated using (true);
create policy "Admin can add objections"
on public.objections for insert to authenticated with check (public.is_app_admin());
create policy "Admin can update objections"
on public.objections for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

create policy "Public can read financial adjustments"
on public.financial_adjustments for select to anon, authenticated using (true);
create policy "Admin can add financial adjustments"
on public.financial_adjustments for insert to authenticated with check (public.is_app_admin());

commit;
