-- Adds player-level monthly payments. Payments settle an account balance rather
-- than individual fines, and reversals preserve the original audit trail.

begin;

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete restrict,
  season_id bigint references public.seasons(id) on delete restrict,
  monthly_period_id bigint references public.monthly_periods(id) on delete restrict,
  period_month date not null,
  amount numeric(10, 2) not null check (amount > 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  payment_method text not null
    check (payment_method in ('cash', 'bank_transfer', 'other')),
  paid_at timestamptz not null default now(),
  admin_note text check (admin_note is null or length(admin_note) <= 500),
  idempotency_key uuid not null unique,
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users(id) on delete restrict,
  reversed_at timestamptz,
  reversed_by uuid references auth.users(id) on delete set null,
  reversal_reason text,
  constraint payments_period_month_first_day_check
    check (period_month = date_trunc('month', period_month)::date),
  constraint payments_reversal_reason_check
    check (
      (reversed_at is null and reversed_by is null and reversal_reason is null)
      or (
        reversed_at is not null
        and reversed_by is not null
        and length(btrim(reversal_reason)) > 0
      )
    )
);

create or replace function public.guard_payment_reversal()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.reversed_at is not null then
    raise exception 'A reversed payment cannot be changed.';
  end if;
  if new.reversed_at is null or new.reversed_by is null
    or nullif(btrim(new.reversal_reason), '') is null then
    raise exception 'A payment update must be a complete reversal.';
  end if;
  return new;
end;
$$;

revoke all on function public.guard_payment_reversal() from public;

drop trigger if exists payments_guard_reversal on public.payments;
create trigger payments_guard_reversal
before update on public.payments
for each row execute function public.guard_payment_reversal();

create index if not exists payments_player_period_idx
on public.payments (player_id, period_month, paid_at desc);

create index if not exists payments_period_active_idx
on public.payments (period_month, paid_at desc)
where reversed_at is null;

alter table public.payments enable row level security;

revoke all privileges on table public.payments from anon, authenticated;

-- Public readers can see only the fields needed to verify account balances.
-- Payment method, the administrator's note, and Auth user IDs remain private.
grant select (
  id, player_id, season_id, monthly_period_id, period_month, amount, currency,
  paid_at, created_at, reversed_at
)
on public.payments to anon, authenticated;

grant insert (
  player_id, season_id, monthly_period_id, period_month, amount, currency,
  payment_method, paid_at, admin_note, idempotency_key, created_by
)
on public.payments to authenticated;

grant update (reversed_at, reversed_by, reversal_reason)
on public.payments to authenticated;

grant usage, select on sequence public.payments_id_seq to authenticated;

drop policy if exists "Public can read payments" on public.payments;
drop policy if exists "Admin can add payments" on public.payments;
drop policy if exists "Admin can reverse payments" on public.payments;

create policy "Public can read payments"
on public.payments for select to anon, authenticated using (true);

create policy "Admin can add payments"
on public.payments for insert to authenticated
with check (public.is_app_admin() and created_by = auth.uid());

create policy "Admin can reverse payments"
on public.payments for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

commit;
