-- Adds administrator-managed exceptions for one player and settlement month.
-- Private reasons are not granted to public readers.

begin;

create table if not exists public.settlement_exceptions (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete restrict,
  monthly_period_id bigint not null references public.monthly_periods(id) on delete restrict,
  custom_deadline date,
  penalties_paused_until date,
  penalties_waived boolean not null default false,
  reason text check (reason is null or length(reason) <= 500),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null references auth.users(id) on delete restrict,
  updated_by uuid references auth.users(id) on delete set null,
  unique (player_id, monthly_period_id),
  constraint settlement_exceptions_rule_check
    check (
      not active
      or custom_deadline is not null
      or penalties_paused_until is not null
      or penalties_waived
    )
);

create index if not exists settlement_exceptions_period_active_idx
on public.settlement_exceptions (monthly_period_id, player_id)
where active;

drop trigger if exists settlement_exceptions_set_updated_at
on public.settlement_exceptions;
create trigger settlement_exceptions_set_updated_at
before update on public.settlement_exceptions
for each row execute function public.set_updated_at();

alter table public.settlement_exceptions enable row level security;

revoke all privileges on table public.settlement_exceptions from anon, authenticated;

grant select (
  id, player_id, monthly_period_id, custom_deadline,
  penalties_paused_until, penalties_waived, active, created_at, updated_at
)
on public.settlement_exceptions to anon, authenticated;

grant insert (
  player_id, monthly_period_id, custom_deadline, penalties_paused_until,
  penalties_waived, reason, active, created_by, updated_by
)
on public.settlement_exceptions to authenticated;

grant update (
  custom_deadline, penalties_paused_until, penalties_waived,
  reason, active, updated_by
)
on public.settlement_exceptions to authenticated;

grant usage, select on sequence public.settlement_exceptions_id_seq
to authenticated;

drop policy if exists "Public can read settlement exceptions"
on public.settlement_exceptions;
drop policy if exists "Admin can add settlement exceptions"
on public.settlement_exceptions;
drop policy if exists "Admin can update settlement exceptions"
on public.settlement_exceptions;

create policy "Public can read settlement exceptions"
on public.settlement_exceptions for select to anon, authenticated using (true);

create policy "Admin can add settlement exceptions"
on public.settlement_exceptions for insert to authenticated
with check (public.is_app_admin() and created_by = auth.uid());

create policy "Admin can update settlement exceptions"
on public.settlement_exceptions for update to authenticated
using (public.is_app_admin()) with check (public.is_app_admin());

commit;
